source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings! #ignore all warnings from all pods

target 'Example' do
	pod 'SVProgressHUD'
	pod 'Uploadcare', :path => '../'
end